version: '3.8'
services:
  elasticsearch:
    image: vivekdhole96/elasticsearch:8.9.0  # Pull from Docker Hub
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: vivekdhole96/logstash:8.9.0  # Pull from Docker Hub
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - C:/Users/DELL/Desktop/elk-stack/robot_logs.json:/usr/share/logstash/logs/robot_logs.json
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch

  kibana:
    image: vivekdhole96/kibana:8.9.0  # Pull from Docker Hub
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  grafana:
    image: vivekdhole96/grafana:latest  # Pull from Docker Hub
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - elasticsearch
      - logstash

volumes:
  es_data:
  grafana_data:
